#! /bin/bash

echo "merging book..."

python merge_book.py > Kalman_and_Bayesian_Filters_in_Python.ipynb

echo "creating pdf..."
ipython nbconvert --to latex --template book Kalman_and_Bayesian_Filters_in_Python.ipynb
ipython to_pdf.py

mv Kalman_and_Bayesian_Filters_in_Python.pdf ..
echo "done."

