#! /bin/bash

#echo "merging book..."
ipython merge_book.py

echo "creating pdf..."
ipython nbconvert --to latex --template book book.ipynb
ipython to_pdf.py

mv Kalman_and_Bayesian_Filters_in_Python.pdf ..


