#! /bin/bash

echo "merging book..."

python merge_book.py > Kalman_and_Bayesian_Filters_in_Python.ipynb

echo "creating pdf..."
ipython nbconvert --to PDF --template book Kalman_and_Bayesian_Filters_in_Python.ipynb

mv Kalman_and_Bayesian_Filters_in_Python.pdf ..
echo "done."

